import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Next Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="next 마스터 하기!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="underline">홈입니다</h1>
    </Layout>
  );
}
