import Layout from "@/components/layout";
import Head from "next/head";
import { TOKEN, DATABASE_ID } from "@/config";
import ProjectItem from "@/components/projects/project-item";

export default function Projects({ projects }) {
  return (
    <>
      <Layout>
        <Head>
          <title>김보영FE Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="next 마스터 하기!" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-4xl font-bold m-6 text-center">
          총 프로젝트 :
          <span className="pl-4 text-purple-500">
            {projects.results.length}
          </span>
        </h1>
        <div className="flex justify-center my-10">
          <div className="grid grid-cols-1 md:grid-cols-2 mx-5  gap-8 w-4/5">
            {projects.results.reverse().map((p) => (
              <div className="flex justify-center">
                <ProjectItem key={p.id} data={p} />
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getStaticProps(context) {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-02-22",
      "content-type": "application/json",
      authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      page_size: 100,
    }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const projects = await res.json();

  return {
    props: { projects }, // will be passed to the page component as props
  };
}
