import Layout from "@/components/layout";
import Head from "next/head";
import { TOKEN, DATABASE_ID } from "@/config";

export default function Projects() {
  return (
    <>
      <Head>
        <title>김보영FE Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="next 마스터 하기!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>프로젝트</h1>
      </Layout>
    </>
  );
}

export async function getStaticProps(context) {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-02-22",
      "content-type": "application/json",
      authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ parent: "string", properties: "string" }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );
  const result = await res.json();

  console.log(result);
  return {
    props: {}, // will be passed to the page component as props
  };
}
