import Layout from "@/components/layout";
import Head from "next/head";

export default function Projects() {
  return (
    <>
      <Head>
        <title>김보영FE Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="next 마스터 하기!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>프로젝트</h1>
      </Layout>
    </>
  );
}
